name: Plan Snowflake Infra
on:
  workflow_dispatch:
    inputs:
      targetEnvironment:
        type: choice
        description: Plan to
        options: 
        - dev
        - prod
        required: true
        default: 'dev'
      alwaysApplyGrants:
        type: choice
        description: Re-run all grants
        options: 
        - false
        - true
        required: true
        default: 'false'
      logDebug:
        type: choice
        description: TF_LOG debug level
        options:
        - TRACE
        - 'OFF'
        required: true
        default: 'OFF'
  workflow_call:
    inputs:
      targetEnvironment:
        required: true
        type: string
        default: dev
      alwaysApplyGrants:
        required: true
        type: string
        default: false
      logDebug:
        required: true
        type: string
        default: OFF

jobs:
  Plan:
    name: Plan Terraform
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.targetEnvironment }}
    defaults:
      run:
        shell: bash
        working-directory: ./
    concurrency: infra-plan
    permissions:
      contents: read # required to checkout the code from the repo

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Set terraform environment variables
      run: |
        # ALL ENVS
        echo "TF_LOG=${{ github.event.inputs.logDebug }}" >> $GITHUB_ENV
        echo "BACKEND_ENCRYPT=true" >> $GITHUB_ENV
        echo "ENVIRONMENT=${{ github.event.inputs.targetEnvironment }}" >> $GITHUB_ENV
        echo "SNOWFLAKE_PRIVATE_KEY_2<<EOF" >> $GITHUB_ENV
        echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY_2 }}" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4.2.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_2 }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_2 }}
        role-duration-seconds: 900
        aws-region: us-east-1

    - name: install terraform
      uses: hashicorp/setup-terraform@v3.1.2
      with:
        terraform_version: 1.12.2
        terraform_wrapper: false

    - name: Initialize Terraform
      run: |
        terraform init -backend-config="./backends/backend-$ENVIRONMENT.tfvars"

    - name: Format terraform
      run: terraform fmt -check

    - name: Validate terraform
      run: terraform validate

    - name: Plan terraform
      run: |
        terraform plan --var-file=./environments/$ENVIRONMENT.tfvars -var always_apply=${{ github.event.inputs.alwaysApplyGrants }} -out=./output.tfplan
